name: Deploy Portfolio React App to Azure

on:
    push:
        branches:
            - master # Deploy on push to the master branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        env: # This section sets environment variables for the entire job
            VITE_IMAGE_BASE_URL: ${{ secrets.IMAGE_S3_URL }}
            VITE_BACKEND_URL: ${{ secrets.BACKEND_URL }}

        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Build and push Docker image to Azure Container Registry (ACR)
            - name: Build and push Docker image to ACR
              run: |
                  echo ${{ secrets.ACR_PASSWORD }} | docker login portfolioreactcontainer.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
                  docker build -t portfolioreactcontainer.azurecr.io/react-app:latest .
                  docker push portfolioreactcontainer.azurecr.io/react-app:latest

            # Deploy to Azure Web App using Publish Profile
            - name: Deploy to Azure Web App using Publish Profile
              uses: azure/webapps-deploy@v2
              with:
                  app-name: portfolio-react-pll # Replace with your actual Azure Web App name
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Publish profile from GitHub Secrets
                  images: portfolioreactcontainer.azurecr.io/react-app:latest # Docker image to deploy
