name: Deploy Portfolio React App to Azure

on:
    push:
        branches:
            - master # Deploy on push to the master branch
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Build and push Docker image to Azure Container Registry (ACR)
            - name: Build and push Docker image to ACR
              run: |
                  echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
                  docker build --build-arg IMAGE_URL=${{ secrets.IMAGE_S3_URL }} \
                               --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} \
                               -t ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/react-app:latest .
                  docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/react-app:latest

            - name: Login to Azure using Service Principal
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ secrets.PORTFOLIO_NAME }}
                  slot-name: 'Production'
                  package: .
